// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetStatus():Promise<main.Status>;

export function LoginNow():Promise<string>;

export function LogoutNow():Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;
